error_log  /var/www/log/error.log;
access_log /var/www/log/access.log;

# Block paths containing '..' (Directory Traversal attempts)
set $blocked 0;
if ($request_uri ~* "\.\.") {
    set $blocked 1;
}

if ($blocked) {
    return 403;
}

location /api/ {
    proxy_pass http://api:8000;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location / {
    proxy_pass http://frontend:3000/;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /_next/static/ {
    proxy_pass http://frontend:3000/_next/static/;
    expires 1y;
    access_log off;
    add_header Cache-Control "public, immutable";
}

location = /favicon.ico {
    log_not_found off;
    access_log off;
}

location = /robots.txt {
    log_not_found off;
    access_log off;
    allow all;
}
