name: Application Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Build And Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: andriykryvenko/argus-frontend

      - name: Build and push Frontend Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./.deploy/frontend.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/andriykryvenko/argus-frontend
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: andriykryvenko/argus-forecast

      - name: Build and push Public Api Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./.deploy/api.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/andriykryvenko/argus-forecast
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  upload_code:
    needs: push_to_registry
    name: Upload code to production server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload compose/files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: ".deploy/docker-compose.yml,.deploy/nginx,.deploy/api.Dockerfile,.deploy/frontend.Dockerfile,.deploy/nginx-proxy-up.sh,configs"
          target: "/var/www"
      
      - name: Restart production containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /var/www
            mkdir -p log/nginx
            mkdir -p log/frontend
            mkdir -p log/api
            mkdir -p data
            mkdir -p models

            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
