name: Application Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Build And Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract frontend metadata (tags, labels) for Docker
        id: metaFrontend
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: andriykryvenko/argus-frontend

      - name: Build and push Frontend Docker image
        id: pushFrontend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./.deploy/frontend.Dockerfile
          push: true
          tags: ${{ steps.metaFrontend.outputs.tags }}
          labels: ${{ steps.metaFrontend.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/andriykryvenko/argus-frontend
          subject-digest: ${{ steps.pushFrontend.outputs.digest }}
          push-to-registry: true
      
      - name: Extract api metadata (tags, labels) for Docker
        id: metaApi
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: andriykryvenko/argus-forecast

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.FORECAST_CORE_DEPLOY_KEY }}

      - name: Build and push Public Api Docker image
        id: pushApi
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./.deploy/api.Dockerfile
          push: true
          tags: ${{ steps.metaApi.outputs.tags }}
          labels: ${{ steps.metaApi.outputs.labels }}
          ssh: default

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/andriykryvenko/argus-forecast
          subject-digest: ${{ steps.pushApi.outputs.digest }}
          push-to-registry: true

  upload_code:
    needs: push_to_registry
    name: Upload code to production server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload compose/files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: ".deploy/docker-compose.yml,.deploy/nginx,.deploy/alloy,.deploy/nginx-proxy-up.sh,configs"
          target: "/var/www"
      
      
      - name: Restart production containers
        uses: appleboy/ssh-action@v1.2.0
        env:
          DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          envs: DOCKERHUB_LOGIN,DOCKERHUB_TOKEN
          script: |
            cd /var/www
            mkdir -p log/nginx log/frontend log/api data models metrics nginx nginx/templates alloy configs
            mv ./.deploy/docker-compose.yml ./
            mv ./.deploy/nginx-proxy-up.sh ./
            mv ./.deploy/nginx/default.conf ./nginx/
            mv ./.deploy/nginx/templates/http.conf.template ./nginx/templates/
            mv ./.deploy/alloy/config.alloy ./alloy/
            mv ./.deploy/cronjobs.txt ./
            rm -rf ./.deploy

            echo "$DOCKERHUB_TOKEN" | docker login \
              --username "$DOCKERHUB_LOGIN" \
              --password-stdin

            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f

            docker compose run --rm --name forecast_update api .venv/bin/python src/commands/generate_wind_forecast.py

            crontab cronjobs.txt
            rm cronjobs.txt
